ENTITIES = {
    0: {'name': 'Allay', 'box_x_z': '0.35', 'box_y': '0.6', 'id': 'minecraft:allay'},
    1: {
        'name': 'Area Effect Cloud',
        'box_x_z': '2.0 * Radius',
        'box_y': '0.5',
        'id': 'minecraft:area_effect_cloud',
    },
    2: {
        'name': 'Armor Stand',
        'box_x_z': 'normal: 0.5 marker: 0.0 small: 0.25',
        'box_y': 'normal: 1.975 marker: 0.0 small: 0.9875',
        'id': 'minecraft:armor_stand',
    },
    3: {'name': 'Arrow', 'box_x_z': '0.5', 'box_y': '0.5', 'id': 'minecraft:arrow'},
    4: {'name': 'Axolotl', 'box_x_z': '0.75', 'box_y': '0.42', 'id': 'minecraft:axolotl'},
    5: {'name': 'Bat', 'box_x_z': '0.5', 'box_y': '0.9', 'id': 'minecraft:bat'},
    6: {'name': 'Bee', 'box_x_z': '0.7', 'box_y': '0.6', 'id': 'minecraft:bee'},
    7: {'name': 'Blaze', 'box_x_z': '0.6', 'box_y': '1.8', 'id': 'minecraft:blaze'},
    8: {'name': 'Block Display', 'box_x_z': '0.0', 'box_y': '0.0', 'id': 'minecraft:block_display'},
    9: {'name': 'Boat', 'box_x_z': '1.375', 'box_y': '0.5625', 'id': 'minecraft:boat'},
    10: {'name': 'Camel', 'box_x_z': '1.7', 'box_y': '2.375', 'id': 'minecraft:camel'},
    11: {'name': 'Cat', 'box_x_z': '0.6', 'box_y': '0.7', 'id': 'minecraft:cat'},
    12: {'name': 'Cave Spider', 'box_x_z': '0.7', 'box_y': '0.5', 'id': 'minecraft:cave_spider'},
    13: {'name': 'Chest Boat', 'box_x_z': '1.375', 'box_y': '0.5625', 'id': 'minecraft:chest_boat'},
    14: {'name': 'Chest Minecart', 'box_x_z': '0.98', 'box_y': '0.7', 'id': 'minecraft:chest_minecart'},
    15: {'name': 'Chicken', 'box_x_z': '0.4', 'box_y': '0.7', 'id': 'minecraft:chicken'},
    16: {'name': 'Cod', 'box_x_z': '0.5', 'box_y': '0.3', 'id': 'minecraft:cod'},
    17: {
        'name': 'Command Block Minecart',
        'box_x_z': '0.98',
        'box_y': '0.7',
        'id': 'minecraft:command_block_minecart',
    },
    18: {'name': 'Cow', 'box_x_z': '0.9', 'box_y': '1.4', 'id': 'minecraft:cow'},
    19: {'name': 'Creeper', 'box_x_z': '0.6', 'box_y': '1.7', 'id': 'minecraft:creeper'},
    20: {'name': 'Dolphin', 'box_x_z': '0.9', 'box_y': '0.6', 'id': 'minecraft:dolphin'},
    21: {'name': 'Donkey', 'box_x_z': '1.3964844', 'box_y': '1.5', 'id': 'minecraft:donkey'},
    22: {'name': 'Dragon Fireball', 'box_x_z': '1.0', 'box_y': '1.0', 'id': 'minecraft:dragon_fireball'},
    23: {'name': 'Drowned', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:drowned'},
    24: {'name': 'Egg', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:egg'},
    25: {
        'name': 'Elder Guardian',
        'box_x_z': '1.9975 (2.35 * guardian)',
        'box_y': '1.9975 (2.35 * guardian)',
        'id': 'minecraft:elder_guardian',
    },
    26: {'name': 'End Crystal', 'box_x_z': '2.0', 'box_y': '2.0', 'id': 'minecraft:end_crystal'},
    27: {'name': 'Ender Dragon', 'box_x_z': '16.0', 'box_y': '8.0', 'id': 'minecraft:ender_dragon'},
    28: {'name': 'Ender Pearl', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:ender_pearl'},
    29: {'name': 'Enderman', 'box_x_z': '0.6', 'box_y': '2.9', 'id': 'minecraft:enderman'},
    30: {'name': 'Endermite', 'box_x_z': '0.4', 'box_y': '0.3', 'id': 'minecraft:endermite'},
    31: {'name': 'Evoker', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:evoker'},
    32: {'name': 'Evoker Fangs', 'box_x_z': '0.5', 'box_y': '0.8', 'id': 'minecraft:evoker_fangs'},
    33: {'name': 'Experience Bottle', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:experience_bottle'},
    34: {'name': 'Experience Orb', 'box_x_z': '0.5', 'box_y': '0.5', 'id': 'minecraft:experience_orb'},
    35: {'name': 'Eye Of Ender', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:eye_of_ender'},
    36: {'name': 'Falling Block', 'box_x_z': '0.98', 'box_y': '0.98', 'id': 'minecraft:falling_block'},
    37: {'name': 'Firework Rocket', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:firework_rocket'},
    38: {'name': 'Fox', 'box_x_z': '0.6', 'box_y': '0.7', 'id': 'minecraft:fox'},
    39: {'name': 'Frog', 'box_x_z': '0.5', 'box_y': '0.5', 'id': 'minecraft:frog'},
    40: {'name': 'Furnace Minecart', 'box_x_z': '0.98', 'box_y': '0.7', 'id': 'minecraft:furnace_minecart'},
    41: {'name': 'Ghast', 'box_x_z': '4.0', 'box_y': '4.0', 'id': 'minecraft:ghast'},
    42: {'name': 'Giant', 'box_x_z': '3.6', 'box_y': '12.0', 'id': 'minecraft:giant'},
    43: {
        'name': 'Glow Item Frame',
        'box_x_z': '0.75 or 0.0625 (depth)',
        'box_y': '0.75',
        'id': 'minecraft:glow_item_frame',
    },
    44: {'name': 'Glow Squid', 'box_x_z': '0.8', 'box_y': '0.8', 'id': 'minecraft:glow_squid'},
    45: {'name': 'Goat', 'box_x_z': '1.3', 'box_y': '0.9', 'id': 'minecraft:goat'},
    46: {'name': 'Guardian', 'box_x_z': '0.85', 'box_y': '0.85', 'id': 'minecraft:guardian'},
    47: {'name': 'Hoglin', 'box_x_z': '1.3964844', 'box_y': '1.4', 'id': 'minecraft:hoglin'},
    48: {'name': 'Hopper Minecart', 'box_x_z': '0.98', 'box_y': '0.7', 'id': 'minecraft:hopper_minecart'},
    49: {'name': 'Horse', 'box_x_z': '1.3964844', 'box_y': '1.6', 'id': 'minecraft:horse'},
    50: {'name': 'Husk', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:husk'},
    51: {'name': 'Illusioner', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:illusioner'},
    52: {'name': 'Interaction', 'box_x_z': '0.0', 'box_y': '0.0', 'id': 'minecraft:interaction'},
    53: {'name': 'Iron Golem', 'box_x_z': '1.4', 'box_y': '2.7', 'id': 'minecraft:iron_golem'},
    54: {'name': 'Item', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:item'},
    55: {'name': 'Item Display', 'box_x_z': '0.0', 'box_y': '0.0', 'id': 'minecraft:item_display'},
    56: {
        'name': 'Item Frame',
        'box_x_z': '0.75 or 0.0625 (depth)',
        'box_y': '0.75',
        'id': 'minecraft:item_frame',
    },
    57: {'name': 'Fireball', 'box_x_z': '1.0', 'box_y': '1.0', 'id': 'minecraft:fireball'},
    58: {'name': 'Leash Knot', 'box_x_z': '0.375', 'box_y': '0.5', 'id': 'minecraft:leash_knot'},
    59: {'name': 'Lightning Bolt', 'box_x_z': '0.0', 'box_y': '0.0', 'id': 'minecraft:lightning_bolt'},
    60: {'name': 'Llama', 'box_x_z': '0.9', 'box_y': '1.87', 'id': 'minecraft:llama'},
    61: {'name': 'Llama Spit', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:llama_spit'},
    62: {
        'name': 'Magma Cube',
        'box_x_z': '0.5202 * size',
        'box_y': '0.5202 * size',
        'id': 'minecraft:magma_cube',
    },
    63: {'name': 'Marker', 'box_x_z': '0.0', 'box_y': '0.0', 'id': 'minecraft:marker'},
    64: {'name': 'Minecart', 'box_x_z': '0.98', 'box_y': '0.7', 'id': 'minecraft:minecart'},
    65: {'name': 'Mooshroom', 'box_x_z': '0.9', 'box_y': '1.4', 'id': 'minecraft:mooshroom'},
    66: {'name': 'Mule', 'box_x_z': '1.3964844', 'box_y': '1.6', 'id': 'minecraft:mule'},
    67: {'name': 'Ocelot', 'box_x_z': '0.6', 'box_y': '0.7', 'id': 'minecraft:ocelot'},
    68: {
        'name': 'Painting',
        'box_x_z': 'type width or 0.0625 (depth)',
        'box_y': 'type height',
        'id': 'minecraft:painting',
    },
    69: {'name': 'Panda', 'box_x_z': '1.3', 'box_y': '1.25', 'id': 'minecraft:panda'},
    70: {'name': 'Parrot', 'box_x_z': '0.5', 'box_y': '0.9', 'id': 'minecraft:parrot'},
    71: {'name': 'Phantom', 'box_x_z': '0.9', 'box_y': '0.5', 'id': 'minecraft:phantom'},
    72: {'name': 'Pig', 'box_x_z': '0.9', 'box_y': '0.9', 'id': 'minecraft:pig'},
    73: {'name': 'Piglin', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:piglin'},
    74: {'name': 'Piglin Brute', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:piglin_brute'},
    75: {'name': 'Pillager', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:pillager'},
    76: {'name': 'Polar Bear', 'box_x_z': '1.4', 'box_y': '1.4', 'id': 'minecraft:polar_bear'},
    77: {'name': 'Potion', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:potion'},
    78: {'name': 'Pufferfish', 'box_x_z': '0.7', 'box_y': '0.7', 'id': 'minecraft:pufferfish'},
    79: {'name': 'Rabbit', 'box_x_z': '0.4', 'box_y': '0.5', 'id': 'minecraft:rabbit'},
    80: {'name': 'Ravager', 'box_x_z': '1.95', 'box_y': '2.2', 'id': 'minecraft:ravager'},
    81: {'name': 'Salmon', 'box_x_z': '0.7', 'box_y': '0.4', 'id': 'minecraft:salmon'},
    82: {'name': 'Sheep', 'box_x_z': '0.9', 'box_y': '1.3', 'id': 'minecraft:sheep'},
    83: {
        'name': 'Shulker',
        'box_x_z': '1.0',
        'box_y': '1.0-2.0 (depending on peek)',
        'id': 'minecraft:shulker',
    },
    84: {'name': 'Shulker Bullet', 'box_x_z': '0.3125', 'box_y': '0.3125', 'id': 'minecraft:shulker_bullet'},
    85: {'name': 'Silverfish', 'box_x_z': '0.4', 'box_y': '0.3', 'id': 'minecraft:silverfish'},
    86: {'name': 'Skeleton', 'box_x_z': '0.6', 'box_y': '1.99', 'id': 'minecraft:skeleton'},
    87: {'name': 'Skeleton Horse', 'box_x_z': '1.3964844', 'box_y': '1.6', 'id': 'minecraft:skeleton_horse'},
    88: {'name': 'Slime', 'box_x_z': '0.5202 * size', 'box_y': '0.5202 * size', 'id': 'minecraft:slime'},
    89: {'name': 'Small Fireball', 'box_x_z': '0.3125', 'box_y': '0.3125', 'id': 'minecraft:small_fireball'},
    90: {'name': 'Sniffer', 'box_x_z': '1.9', 'box_y': '1.75', 'id': 'minecraft:sniffer'},
    91: {'name': 'Snow Golem', 'box_x_z': '0.7', 'box_y': '1.9', 'id': 'minecraft:snow_golem'},
    92: {'name': 'Snowball', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:snowball'},
    93: {'name': 'Spawner Minecart', 'box_x_z': '0.98', 'box_y': '0.7', 'id': 'minecraft:spawner_minecart'},
    94: {'name': 'Spectral Arrow', 'box_x_z': '0.5', 'box_y': '0.5', 'id': 'minecraft:spectral_arrow'},
    95: {'name': 'Spider', 'box_x_z': '1.4', 'box_y': '0.9', 'id': 'minecraft:spider'},
    96: {'name': 'Squid', 'box_x_z': '0.8', 'box_y': '0.8', 'id': 'minecraft:squid'},
    97: {'name': 'Stray', 'box_x_z': '0.6', 'box_y': '1.99', 'id': 'minecraft:stray'},
    98: {'name': 'Strider', 'box_x_z': '0.9', 'box_y': '1.7', 'id': 'minecraft:strider'},
    99: {'name': 'Tadpole', 'box_x_z': '0.4', 'box_y': '0.3', 'id': 'minecraft:tadpole'},
    100: {'name': 'Text Display', 'box_x_z': '0.0', 'box_y': '0.0', 'id': 'minecraft:text_display'},
    101: {'name': 'Tnt', 'box_x_z': '0.98', 'box_y': '0.98', 'id': 'minecraft:tnt'},
    102: {'name': 'Tnt Minecart', 'box_x_z': '0.98', 'box_y': '0.7', 'id': 'minecraft:tnt_minecart'},
    103: {'name': 'Trader Llama', 'box_x_z': '0.9', 'box_y': '1.87', 'id': 'minecraft:trader_llama'},
    104: {'name': 'Trident', 'box_x_z': '0.5', 'box_y': '0.5', 'id': 'minecraft:trident'},
    105: {'name': 'Tropical Fish', 'box_x_z': '0.5', 'box_y': '0.4', 'id': 'minecraft:tropical_fish'},
    106: {'name': 'Turtle', 'box_x_z': '1.2', 'box_y': '0.4', 'id': 'minecraft:turtle'},
    107: {'name': 'Vex', 'box_x_z': '0.4', 'box_y': '0.8', 'id': 'minecraft:vex'},
    108: {'name': 'Villager', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:villager'},
    109: {'name': 'Vindicator', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:vindicator'},
    110: {'name': 'Wandering Trader', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:wandering_trader'},
    111: {'name': 'Warden', 'box_x_z': '0.9', 'box_y': '2.9', 'id': 'minecraft:warden'},
    112: {'name': 'Witch', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:witch'},
    113: {'name': 'Wither', 'box_x_z': '0.9', 'box_y': '3.5', 'id': 'minecraft:wither'},
    114: {'name': 'Wither Skeleton', 'box_x_z': '0.7', 'box_y': '2.4', 'id': 'minecraft:wither_skeleton'},
    115: {'name': 'Wither Skull', 'box_x_z': '0.3125', 'box_y': '0.3125', 'id': 'minecraft:wither_skull'},
    116: {'name': 'Wolf', 'box_x_z': '0.6', 'box_y': '0.85', 'id': 'minecraft:wolf'},
    117: {'name': 'Zoglin', 'box_x_z': '1.3964844', 'box_y': '1.4', 'id': 'minecraft:zoglin'},
    118: {'name': 'Zombie', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:zombie'},
    119: {'name': 'Zombie Horse', 'box_x_z': '1.3964844', 'box_y': '1.6', 'id': 'minecraft:zombie_horse'},
    120: {'name': 'Zombie Villager', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:zombie_villager'},
    121: {'name': 'Zombified Piglin', 'box_x_z': '0.6', 'box_y': '1.95', 'id': 'minecraft:zombified_piglin'},
    122: {'name': 'Player', 'box_x_z': '0.6', 'box_y': '1.8', 'id': 'minecraft:player'},
    123: {'name': 'Fishing Bobber', 'box_x_z': '0.25', 'box_y': '0.25', 'id': 'minecraft:fishing_bobber'},
}
